aws_profile: [default]
app: demo-lambda-test
region: ap-northeast-2
# roleArn: arn:aws:iam::12345678910:role/demo-iam-role
env:
  test_value: my_test

test_targets:
- uri: ddb/put.js
  description: testDDB
  method: put
  parms:
    email: spark@rubywave.io
    company_name: rubywave
    type: test
- uri: ddb/get.js
  description: testDDB
  method: get
  parms:
    hash_key: hash_test
